### PR TITLE
Questions

### PR DESCRIPTION
**Pull request by ashifkhn**
Question page, cateogory and result page added in Quiz app.

### CODE REVIEW

**Review by Pratham82 — APPROVED** [review]
All features working as expected.
Suggestions/ changes:
1. Change answer selection color based on answer's correctness.
2. Add final score in the results page.

**Review by sakshi006 — APPROVED** [review]
Looks good. Everything is working fine. Use CSS variables for applying styles.
Also, fix these typos.
Screenshot (766)
Screenshot (767)

**Comment by ashifkhn** [comment]
> All features working as expected. Suggestions/ changes:
> 
> 1. Change answer selection color based on answer's correctness.
> 2. Add final score in the results page.

I will refactor in next pr

**Comment by ashifkhn** [comment]
> Looks good. Everything is working fine. Use CSS variables for applying styles. Also, fix these typos. Screenshot (766) Screenshot (767)

I will refactor in next pr

**Pull request merged**
